# Numpy 

In [2]:
import numpy as np
a=np.random.randint(0, 5, size=(3,3))

In [3]:
a

array([[4, 3, 3],
       [0, 1, 1],
       [3, 4, 4]])

In [4]:
a.sum()

23

In [5]:
a.sum(axis=0)

array([7, 8, 8])

In [6]:
a.sum(axis=1)

array([10,  2, 11])

In [7]:
(a > 2).any(1)

array([ True, False,  True])

In [8]:
a.sort()

In [9]:
a

array([[3, 3, 4],
       [0, 1, 1],
       [3, 4, 4]])

In [10]:
a.sort(0)

In [11]:
a

array([[0, 1, 1],
       [3, 3, 4],
       [3, 4, 4]])

In [12]:
import pandas as pd
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'A': [7, 8, 9], 'B': [10, 11, 12]})
concatenated_df = pd.concat([df1, df2], ignore_index=True)
concatenated_df

A   B
0  1   4
1  2   5
2  3   6
3  7  10
4  8  11
5  9  12

In [13]:
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'A': [7, 8, 9], 'B': [10, 11, 12]})
df1 = df1.append(df2, ignore_index=True)
df1

AttributeError: 'DataFrame' object has no attribute 'append'

In [24]:
cat = pd.Categorical(['a', 'b', 'c', 'a', 'b', 'c'])
print(cat)

['a', 'b', 'c', 'a', 'b', 'c']
Categories (3, object): ['a', 'b', 'c']


In [25]:
import pandas as pd
import numpy as np
cat = pd.Categorical(["a", "c", "c", np.nan], categories=["b", "a", "c"])
df = pd.DataFrame({"cat": cat, "s":["a", "c", "c", np.nan]})
print(df.describe())
print(df["cat"].describe())

       cat  s
count    3  3
unique   2  2
top      c  c
freq     2  2
count     3
unique    2
top       c
freq      2
Name: cat, dtype: object
